apiVersion: v1
kind: Namespace
metadata:
  name: influxdb
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: influxdb
  namespace: influxdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: influxdb
    spec:
      containers:
      - image: influxdb
        imagePullPolicy: Always
        name: influxdb
        ports:
        - containerPort: 8086
          protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influxdb
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8086
  selector:
    run: influxdb
  type: LoadBalancer
